name: Deploy Development

on:
  push:
    branches:
      - dev
  workflow_run:
    workflows:
      - CI
    branches:
      - dev
    types:
      - completed

permissions:
  actions: read
  contents: read

concurrency:
  group: development
  cancel-in-progress: false

jobs:
  deploy:
    # if: >
    #   github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-24.04

    environment:
      name: development

    steps:
      - name: Download release artifact
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: plankenart-release
          path: release

      - name: Create release archive
        run: |
          tar -czf release.tar.gz -C release .

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan \
            -p ${{ secrets.DEV_PORT }} \
            ${{ secrets.DEV_HOST }} >> ~/.ssh/known_hosts

      - name: Upload release
        run: |
          scp \
            -P ${{ secrets.DEV_PORT }} \
            release.tar.gz \
            ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:/tmp/release.tar.gz

      - name: Deploy
        run: |
          ssh \
            -p ${{ secrets.DEV_PORT }} \
            ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }} \
            "/var/www/plankenart/scripts/deploy.sh /tmp/release.tar.gz"